server:
  port: 8080

spring:
  application:
    name: USER-SERVICE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://130.211.199.78:3306/seeder
    username: root
    password: system
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  # flyway:
  #   baseline-on-migrate: true
  #   locations: classpath:db/migration
  #   debug: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

security:
  ignored: /actuator/health, /actuator/info  # Allow access without authentication


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://service-registry-107202934169.us-central1.run.app/eureka/
  instance:
    prefer-ip-address: false
    hostname: user-service-107202934169.us-central1.run.app 
    non-secure-port-enabled: false
    secure-port-enabled: true
    status-page-url: https://user-service-107202934169.us-central1.run.app/actuator/info
    health-check-url: https://user-service-107202934169.us-central1.run.app/actuator/health
    
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day