server:
  port: 9003

spring:
  application:
    name: CASHKICK-SERVICE
  datasource:
    url: jdbc:mysql://130.211.199.78:3306/seeder
    username: root
    password: system
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
instance:
    prefer-ip-address: false
    hostname: cashkick-service-107202934169.us-central1.run.app
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://service-registry-107202934169.us-central1.run.app/eureka/