
server:
  port: 9004

spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:mysql://130.211.199.78:3306/seeder
    username: root
    password: system
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://service-registry-107202934169.us-central1.run.app/eureka/
  instance:
    prefer-ip-address: false
    hostname: payment-service-107202934169.us-central1.run.app
    non-secure-port-enabled: false
    secure-port-enabled: true
    status-page-url: https://payment-service-107202934169.us-central1.run.app/actuator/info
    health-check-url: https://payment-service-107202934169.us-central1.run.app/actuator/health


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

security:
  ignored: /actuator/health, /actuator/info  # Allow access without authentication
