server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: USER-SERVICE
          uri: https://user-service-107202934169.us-central1.run.app
          predicates:
            - Path=/users/**
        - id: CASHKICK-SERVICE
          uri: https://cashkick-service-107202934169.us-central1.run.app
          predicates:
            - Path=/cashkicks/**
          filters:
            - AuthenticationFilter
        - id: CONTRACT-SERVICE
          uri: https://contract-service-107202934169.us-central1.run.app
          predicates:
            - Path=/contracts/**
          filters:
            - AuthenticationFilter
        - id: PAYMENT-SERVICE
          uri: https://payment-service-107202934169.us-central1.run.app
          predicates:
            - Path=/payments/**
          filters:
            - AuthenticationFilter


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://service-registry-107202934169.us-central1.run.app/eureka/


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970