server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: CASHKICK-SERVICE
          uri: lb://CASHKICK-SERVICE
          predicates:
            - Path=/cashkicks/**
          # filters:
          #   - AuthenticationFilter
        - id: CONTRACT-SERVICE
          uri: lb://CONTRACT-SERVICE
          predicates:
            - Path=/contracts/**
          # filters:
          #   - AuthenticationFilter
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
          # filters:
          #   - AuthenticationFilter


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://service-registry-107202934169.us-central1.run.app/eureka/
  instance:
    prefer-ip-address: false
    hostname: api-gateway-107202934169.us-central1.run.app
    non-secure-port-enabled: false
    secure-port-enabled: true
    status-page-url: https://api-gateway-107202934169.us-central1.run.app/actuator/info
    health-check-url: https://api-gateway-107202934169.us-central1.run.app/actuator/health

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970